from __future__ import annotations

from pathlib import Path

import pandas as pd


def markdown_table(
    rows: list[dict[str, object]],
    columns: list[str],
) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    body = [
        "| " + " | ".join(str(row.get(column, "")) for column in columns) + " |"
        for row in rows
    ]
    return "\n".join([header, separator, *body])


def write_model_report(
    *,
    path: Path,
    dataset_path: Path,
    features: pd.DataFrame,
    train: pd.DataFrame,
    train_examples: int,
    test: pd.DataFrame,
    metrics: pd.DataFrame,
    calibration: pd.DataFrame,
    confidence: pd.DataFrame,
    top_positive: pd.DataFrame,
    top_negative: pd.DataFrame,
    cached_fighters: int,
) -> None:
    metric_rows = [
        {
            "Model / Rule": row["model"],
            "Accuracy": f"{row['accuracy']:.1%}",
            "Log Loss": f"{row['log_loss']:.3f}",
            "Brier": f"{row['brier']:.3f}",
        }
        for _, row in metrics.iterrows()
    ]
    calibration_rows = [
        {
            "Probability Bucket": row["probability_bucket"],
            "Fights": int(row["count"]),
            "Avg Predicted": (
                "" if pd.isna(row["avg_predicted_probability"]) else f"{row['avg_predicted_probability']:.1%}"
            ),
            "Actual Win Rate": (
                "" if pd.isna(row["actual_fighter_a_win_rate"]) else f"{row['actual_fighter_a_win_rate']:.1%}"
            ),
        }
        for _, row in calibration.iterrows()
    ]
    confidence_rows = [
        {
            "Confidence Bucket": row["confidence_bucket"],
            "Fights": int(row["count"]),
            "Avg Confidence": "" if pd.isna(row["avg_confidence"]) else f"{row['avg_confidence']:.1%}",
            "Accuracy": "" if pd.isna(row["accuracy"]) else f"{row['accuracy']:.1%}",
        }
        for _, row in confidence.iterrows()
    ]
    positive_rows = [
        {"Feature": row["feature"], "Coefficient": f"{row['coefficient']:.3f}"}
        for _, row in top_positive.head(8).iterrows()
    ]
    negative_rows = [
        {"Feature": row["feature"], "Coefficient": f"{row['coefficient']:.3f}"}
        for _, row in top_negative.head(8).iterrows()
    ]

    report = f"""# Model Report

This report is generated by `python3 src/train_baseline.py`.

## Dataset

| Item | Value |
| --- | --- |
| Dataset file | `{dataset_path.name}` |
| Feature rows | {len(features):,} |
| Feature columns | {features.shape[1]:,} |
| Train rows | {len(train):,} |
| Training examples | {train_examples:,} |
| Test rows | {len(test):,} |
| Train period | {train["event_date"].min().date()} to {train["event_date"].max().date()} |
| Test period | {test["event_date"].min().date()} to {test["event_date"].max().date()} |
| Cached fighter profiles | {cached_fighters:,} |

## Evaluation

{markdown_table(metric_rows, ["Model / Rule", "Accuracy", "Log Loss", "Brier"])}

## Calibration

{markdown_table(calibration_rows, ["Probability Bucket", "Fights", "Avg Predicted", "Actual Win Rate"])}

## Confidence

{markdown_table(confidence_rows, ["Confidence Bucket", "Fights", "Avg Confidence", "Accuracy"])}

## Largest Positive Coefficients

These features pushed predictions toward Fighter A in the current baseline.

{markdown_table(positive_rows, ["Feature", "Coefficient"])}

## Largest Negative Coefficients

These features pushed predictions toward Fighter B in the current baseline.

{markdown_table(negative_rows, ["Feature", "Coefficient"])}

## Notes

This is a baseline model. Coefficients are useful for debugging, but they should
not be treated as causal explanations because many features overlap.
"""
    path.write_text(report)
